### ISSUE TITLE
No module named dolfin

### ISSUE THREAD

**Issue by kingyin3613** [pprachas/fenics_arclength#12]
Hi, I'm still trying to install fenics_arclength in Windows+Docker environment through the following commands:

> docker pull quay.io/fenicsproject/stable:current
> docker run -ti quay.io/fenicsproject/stable:current
> pip install --user git+https://github.com/pprachas/fenics_arclength.git@master

It turned out that I still could not run any fenics_arclength examples and validations using pip install, hence I switched to clone and install like:

> docker pull quay.io/fenicsproject/stable:current
> docker run -ti quay.io/fenicsproject/stable:current
> git clone https://github.com/pprachas/fenics_arclength.git
> cd fenics_arclength
> pip install --user .
> cd validation
> python validate_3Dbeamsmall.py

An error occurred:
```
Traceback (most recent call last):
  File "validate_bilayer.py", line 1, in <module>
    from dolfin import *
ImportError: No module named dolfin
```

I tried to fix the problem with these solutions: https://fenicsproject.discourse.group/t/modulenotfounderror-no-module-named-dolfin/11427/2  and  https://fenicsproject.discourse.group/t/no-module-named-dolfin-ubuntu-20-04/4528. 
However, none of these worked. 

Then I tried to use Mac OS to install fenics-arclength by:

> git clone https://github.com/pprachas/fenics_arclength.git
> cd fenics_arclength
> pip install --user .
> cd validation
> python validate_3Dbeamsmall.py

it raised the same error:
```
Traceback (most recent call last):
  File "validate_bilayer.py", line 1, in <module>
    from dolfin import *
ImportError: No module named dolfin
```

I'm thinking of an alternative solution, could you please provide a more detailed step-by-step installation to example-run guidance for users who never used Fenics before? That would be very helpful!

Hao

**Comment by pprachas** [comment]
Hi @kingyin3613 

As a quick debug you can check the python version by ``python --version``
If your default python version is is python 2 then FEniCS is not supported.

In this case you will need to use ``python3`` command to run scripts (i.e. ``python3 validate_3Dbeamsmall.py``) -- we have already specified this in the instruction of running the validation scripts. We also recommend running the beam examples first as they are faster than the bilayer examples. 

Please let us know if this works! If not, we will take another look!

**Comment by kingyin3613** [comment]
Hi @pprachas, `python3 validate_3Dbeamsmall.py` worked! Thanks for your prompt rely. I will proceed to check the results soon!
